find_package(GLFW REQUIRED)
include_directories(${GLFW_INCLUDE_DIRS})
add_definitions(${GLFW_DEFINITIONS})
if(NOT GLFW_FOUND)
    message(ERROR " GLFW not found!")
else()
    add_definitions(-DWITH_GLFW)
    list(APPEND COMMON_LIBS ${GLFW_LIBRARIES})
endif()
