if(APPLE)
    # OpenCV found through PkgConfig
    find_package(PkgConfig)
    if(PKGCONFIG_FOUND)
        pkg_check_modules(OPENCV opencv)
        list(APPEND COMMON_LIBS ${OPENCV_LDFLAGS})
        include_directories(${OPENCV_INCLUDE_DIRS})
        if(OPENCV_FOUND)
            add_definitions(-DWITH_OPENCV)
        endif()
    endif()
else()
    message(ERROR "FindOpenCV necessary")
endif()
